name: push-to-master
on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make install
      - run: make unit-test
  smoketests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make build
      - run: make up
      - run: make int-test
      - run: make down
  deploy:
    needs: [ build, smoketests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: terraform steps
